import type { Metadata } from "next";
import { IBM_Plex_Sans } from "next/font/google";
import "./globals.css";
import AuthProvider from "./providers/auth-provider";
import { Toaster } from "sonner";
import QueryClientProvider from "./providers/query-client-provider";
import 'quill/dist/quill.snow.css'

const ibmPlexSans = IBM_Plex_Sans({
  variable: "--font-ibm-plex-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], 
  display: "swap",
});

export const metadata: Metadata = {
  title: "ExploreEase",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={ibmPlexSans.variable}>
      <body className="antialiased flex min-h-screen w-full flex-col">
        <QueryClientProvider>
          <Toaster richColors position="top-right" closeButton />
          <AuthProvider>
            {children}
          </AuthProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
